"""add ai summary to symptoms

Revision ID: 720b0aa61ee7
Revises: 6d53565b5d2b
Create Date: 2026-08-23 11:34:04.548440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '720b0aa61ee7'
down_revision: Union[str, Sequence[str], None] = '6d53565b5d2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('symptoms', sa.Column('ai_summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('symptoms', 'ai_summary')
    # ### end Alembic commands ###
