"""add doctor verification table

Revision ID: 75d638e9b721
Revises: 0e411d946f98
Create Date: 2026-08-23 10:19:50.004495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75d638e9b721'
down_revision: Union[str, Sequence[str], None] = '0e411d946f98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('government_id_number', sa.String(length=100), nullable=False),
    sa.Column('medical_license_number', sa.String(length=100), nullable=False),
    sa.Column('specialization', sa.String(length=150), nullable=False),
    sa.Column('hospital', sa.String(length=150), nullable=False),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('appointments', 'reason',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    op.create_unique_constraint('uq_doctor_appointment_time', 'appointments', ['doctor_id', 'appointment_time'])
    op.drop_column('appointments', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_doctor_appointment_time', 'appointments', type_='unique')
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)
    op.alter_column('appointments', 'reason',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_table('doctor_verifications')
    # ### end Alembic commands ###
