"""add google calendar event id

Revision ID: a8db618b0b27
Revises: 541e9943ecf3
Create Date: 2026-08-23 16:56:56.065380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8db618b0b27'
down_revision: Union[str, Sequence[str], None] = '541e9943ecf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('google_calendar_event_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'google_calendar_event_id')
    # ### end Alembic commands ###
